src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Commentaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $texte;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commentaire")
     * @ORM\JoinColumn(onDelete = "CASCADE")
     */
    private $auteur_id;

    /**
     * @ORM\ManyToOne(targetEntity=Photo::class, inversedBy="commentaires")
     * @ORM\JoinColumn(onDelete = "CASCADE")
     */
    private $photo_id;

    /**
     * @ORM\Column(type="datetime", options={"default": "CURRENT_TIMESTAMP"})
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(?string $texte): self
    {
        $this->texte = $texte;

        return $this;
    }

    public function getAuteurId(): ?User
    {
        return $this->auteur_id;
    }

    public function setAuteurId(?User $auteur_id): self
    {
        $this->auteur_id = $auteur_id;

        return $this;
    }

    public function getPhotoId(): ?Photo
    {
        return $this->photo_id;
    }

    public function setPhotoId(?Photo $photo_id): self
    {
        $this->photo_id = $photo_id;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
    /**
     * @ORM\PrePersist
     */
    public function seTimesStamps(){
        $this->setCreatedAt(new \DateTime());
    }
}

templates/display/all-albums.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Albums{% endblock %}

{% block body %}

    {#  {%  include 'component/inputAddPhoto.html.twig' %} #}

    <section class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12">
        <p class="text-sm text-blue-400 italic mb-12"><a class="hover:text-gray-300 transform transition duration-500 underline" href="{{ path('home') }}">PAGE D'ACCUEIL_</a>
            <span class="text-xs"> / Tous les albums</span>
        </p>

        {% for message in app.flashes('supp') %}
            <div class="bg-red-500 text-white text-center italic text-sm w-1/3 rounded-full py-1 my-4 my-6 mx-auto">
                {{ message }}
            </div>
        {% endfor %}


        <div class="flex justify-end mb-3 hover:text-red-400 text-gray-200 transform transition duration-500">
            {% if toggleBtn == true %}
                <a href="{{ path('displayAllAlbumAlpha')  }}" >
                    <div><i class="fas fa-arrow-circle-up"></i> Voir par ordre alphabétique <i class="fas fa-arrow-circle-up"></i></div>
                </a>
            {% else %}
                <a href="{{ path('displayAllAlbumNonAlpha')  }}" >
                    <div><i class="fas fa-arrow-circle-down"></i> Voir par order non alphabétique <i class="fas fa-arrow-circle-down"></i></div>
                </a>
            {% endif %}
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {% for album in albumList %}
                <div class="h-80 w-full bg-gradient-to-b from-gray-600 to-gray-400 rounded-lg shadow-lg justify-center p-2 flex flex-col">
                    <div class="text-center mb-1 text-white">
                        <a href= "{{ path('displayOneTheme', {idTheme:album.theme.id, titreTheme:album.theme.titre})  }}" >
                            <p class="text-base hover:text-blue-500 transform transition duration-500">{{ album.theme.titre|upper }}</p>
                        </a>
                    </div>
                    <div class="text-center mb-1 text-white">
                        <a href= "{{ path('displayOneAlbumAntiChrono', {idAlbum:album.id, titleAlbum:album.titre})  }}" >
                            <p class="text-base hover:text-blue-500 transform transition duration-500">{{ album.titre }}</p>
                        </a>
                    </div>
                    <div class="h-3/6 mb-4">
                        {% set equi = '' %}
                        {% for photo in photoList %}
                            {%  if photo.album.id == album.id %}
                                {% set equi = photo.file %}
                            {% endif %}
                        {% endfor %}
                        {% if equi == '' %}
                            <img class="border border-1 border-blue-700 shadow-lg rounded-lg object-center object-cover h-full w-full" src='{{ asset('img/unexist.jpg') }}' alt="Pas de photo">
                        {% else %}
                            <a href= "{{ path('displayOneAlbumAntiChrono', {idAlbum:album.id, titleAlbum:album.titre})  }}" >
                                {% if uploadImagesDestination is same as('local') %}
                                    <img class="border border-1 border-blue-700 shadow-lg rounded-lg object-center object-cover h-full w-full" src='{{ asset('uploads/'~equi) }}' alt="Photo de couverture">
                                {% else %}
                                    <img class="border border-1 border-blue-700 shadow-lg rounded-lg object-center object-cover h-full w-full" src='{{ urlCloudinary~equi }}' alt="Photo de couverture">
                                {% endif %}
                            {% endif %}
                            </a>
                    </div>

                    <div class="text-center mb-1">
                        {% if album.annee == null %}
                            <p class="text-base italic text-gray-800 hover:font-bold">Sans date</p>
                        {% else %}
                            <p class="text-base text-gray-800 hover:font-bold">{{ album.annee }}</p>
                        {% endif %}
                    </div>

                    <div class="border-b-2 my-1 border-gray-500 w-full"></div>

                    <div class="text-base italic text-gray-800">
                        {% if  album.photos | length == 0 %}
                            <p> Aucune photo </p>
                        {% elseif album.photos | length == 1  %}
                            <p>  {{ album.photos | length }} photo </p>
                        {% else %}
                            <p>  {{ album.photos | length }} photos </p>
                        {% endif %}
                    </div>

                    {% if is_granted('ROLE_ADMIN') %}
                        <div class="ml-auto h-1/6">
                            <a href="{{ path('deleteAlbum', {idAlbum:album.id}) }}" onclick="return confirm('Confirmer la suppression de cet album ?')" title="supprimer la photo" class="px-2 py-1 text-xs border border-solid border-blue-500 hover:border-red-700 rounded-full text-red-700 bg-transparent hover:bg-red-700 hover:scale-105 hover:text-white transform transition duration-500">
                                X
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </section>

{% endblock %}

templates/display/all-photos.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Photos{% endblock %}

{% block body %}

    {#  {%  include 'component/inputAddPhoto.html.twig' %} #}

    <section class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12">

        <p class="text-sm text-blue-400 italic mb-12"><a class="hover:text-gray-300 transform transition duration-500 underline" href="{{ path('home') }}">PAGE D'ACCUEIL_</a>
            <span class="text-xs"> / Toutes les photos</span>
        </p>

        {% for message in app.flashes('supp') %}
            <div class="bg-red-500 text-white text-center italic text-sm w-1/3 rounded-full py-1 my-4 my-6 mx-auto">
                {{ message }}
            </div>
        {% endfor %}


        <div class="flex justify-end mb-3 hover:text-red-400 text-gray-200 transform transition duration-500">
            {% if toggleBtn == true %}
                <a href="{{ path('displayAllPhotoChrono')  }}" >
                    <div><i class="fas fa-arrow-circle-up"></i> Voir de la plus ancienne à plus récente <i class="fas fa-arrow-circle-up"></i></div>
                </a>
            {% else %}
                <a href="{{ path('displayAllPhotoAntiChrono')  }}" >
                    <div><i class="fas fa-arrow-circle-down"></i> Voir de la plus récente à la plus ancienne <i class="fas fa-arrow-circle-down"></i></div>
                </a>
            {% endif %}
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {% for photo in photoAllList %}
                {% set equi = '' %}
                {% set equi = photo.file %}
                <div class="h-80 w-full bg-gradient-to-b from-gray-600 to-gray-400 rounded-lg shadow-lg justify-center p-2 flex flex-col">
                    <div class="h-3/6 mb-1">
                        <a href= "{{ path('detailsPhoto', {idPhoto:photo.id, titleAlbum:photo.album.titre, status:"view" } ) }}" >
                            {% if uploadImagesDestination is same as('local') %}
                                <img class="border border-1 border-blue-700 shadow-lg rounded-lg object-center object-cover h-full w-full" src='{{ asset('uploads/'~equi) }}' alt="Photo de couverture">
                            {% else %}
                                <img class="border border-1 border-blue-700 shadow-lg rounded-lg object-center object-cover h-full w-full" src='{{ urlCloudinary~equi }}' alt="Photo de couverture">
                            {% endif %}

                                </a>
                    </div>
                    <div class="text-center mb-2">
                        <p class="text-base text-left text-gray-800 font-bold">Theme:</p>
                        <a href="{{ path('displayOneTheme', {idTheme:photo.album.theme.id, titreTheme:photo.album.theme.titre} )  }}" >
                            <p class="text-base text-gray-800 hover:font-bold hover:text-blue-600 hover:underline">{{ photo.album.theme | upper }}</p>
                        </a>
                    </div>
                    <div class="border-b-2 border-gray-500 w-full"></div>
                    <div class="text-center mb-1">
                        <p class="text-base text-left text-gray-800 font-bold">Album:</p>
                        <a href= "{{ path('displayOneAlbumAntiChrono', {idAlbum:photo.album.id, titleAlbum:photo.album.titre})  }}" >
                            <p class="text-base text-gray-800 hover:font-bold hover:text-blue-600 hover:underline">{{ photo.album.titre }}</p>
                        </a>
                    </div>
                    {% if photo.annee == null %}
                        <div class="text-center">
                            <p class="text-base text-gray-800 font-normal italic">"Année non renseignée"</p>
                        </div>
                    {% else %}
                        <div class="h-text-center">
                            <a href="{{ path('displaySingleYear', {photoAnnee:photo.annee} )  }}" >
                                <p class="text-base text-center text-gray-800 font-bold hover:text-blue-600 hover:underline">{{ photo.annee }}</p>
                            </a>
                        </div>
                    {% endif %}
                    {% if is_granted('ROLE_ADMIN') %}
                        <div class="ml-auto">
                            <a href="{{ path('deletePhotoFromAllPhotos', {idPhoto:photo.id}) }}" onclick="return confirm('Confirmer la suppression de cette photo ?')" title="supprimer la photo" class="px-2 py-1 text-xs border border-solid border-blue-500 hover:border-red-700 rounded-full text-red-700 bg-transparent hover:bg-red-700 hover:scale-105 hover:text-white transform transition duration-500">
                                X
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </section>

{% endblock %}

templates/display/all-themes.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Themes{% endblock %}

{% block body %}

    {#  {%  include 'component/inputAddPhoto.html.twig' %} #}

    <section class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12">

        <p class="text-sm text-blue-400 italic mb-12"><a class="hover:text-gray-300 transform transition duration-500 underline" href="{{ path('home') }}">PAGE D'ACCUEIL_</a>
            <span class="text-xs"> / Tous les thèmes</span>
        </p>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-4 gap-8 mt-5">
            {% for theme in themeList %}
                {% if  theme.albums | length == 0 %}
                        <div class="w-full bg-gradient-to-b from-gray-600 to-gray-400 text-gray-800 rounded-lg shadow-lg overflow-hidden justify-center items-center items-stretch cursor-not-allowed">
                            <div class="text-center text-3xl text-gray-800 font-bold py-4">
                              {{ theme.titre | upper }}
                            </div>
                            <div class="text-right text-sm pr-2 pb-2 italic">Pas d'album</div>
                        </div>
                {% elseif theme.albums | length == 1 %}
                    <a href="{{ path('displayOneTheme', {idTheme:theme.id, titreTheme:theme.titre} )  }}" >
                        <div class="w-full bg-gradient-to-b from-gray-600 to-gray-400 text-gray-800 rounded-lg shadow-lg overflow-hidden justify-center items-center items-stretch">
                            <div class="text-center hover:text-white text-3xl font-bold py-4 transform transition duration-500">
                                {{ theme.titre | upper }}
                            </div>
                            <div class="text-right text-sm pr-2 pb-2 italic">{{ theme.albums | length }} album</div>
                        </div>
                    </a>
                {% else %}
                    <a href="{{ path('displayOneTheme', {idTheme:theme.id, titreTheme:theme.titre} )  }}" >
                        <div class="w-full bg-gradient-to-b from-gray-600 to-gray-400 text-gray-800 rounded-lg shadow-lg overflow-hidden justify-center items-center items-stretch">
                            <div class="text-center hover:text-white text-3xl font-bold py-4 transform transition duration-500">
                                {{ theme.titre | upper }}
                            </div>
                            <div class="text-right text-sm pr-2 pb-2 italic">{{ theme.albums | length }} albums</div>
                        </div>
                    </a>
            {% endif %}
            {% endfor %}
        </div>
    </section>

{% endblock %}

templates/display/all-years.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Themes{% endblock %}

{% block body %}

   {#  {%  include 'component/inputAddPhoto.html.twig' %} #}

    <section class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12">

        <p class="text-sm text-blue-400 italic mb-12"><a class="hover:text-gray-300 transform transition duration-500 underline" href="{{ path('home') }}">PAGE D'ACCUEIL_</a>
            <span class="text-xs"> / Toutes les années</span>
        </p>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-4 gap-8 mt-5">
            {% for year in yearListSortedUnique %}
                {% if year == null %}
                    <a href="{{ path('displaySingleYear', {photoAnnee:0000} )  }}" > <div class="hover:bg-blue-600   w-full bg-gradient-to-b from-gray-600 to-gray-400 rounded-lg shadow-lg overflow-hidden flex justify-center items-center items-stretch">
                            <div class="text-center hover:text-white text-3xl text-gray-800 font-bold mb-2 py-8 sm:py-6 transform transition duration-500">
                                SANS DATE
                            </div>
                        </div>
                    </a>
                {% else %}
                    <a href="{{ path('displaySingleYear', {photoAnnee:year} )  }}" >
                        <div class="w-full bg-gradient-to-b from-gray-600 to-gray-400 rounded-lg shadow-lg overflow-hidden flex justify-center items-center items-stretch">
                            <div class="text-center hover:text-white text-3xl text-gray-800 font-bold mb-2 py-8 sm:py-6 transform transition duration-500">
                                {{ year }}
                            </div>
                        </div>
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    </section>

{% endblock %}

templates/display/detailsPhoto.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails Photo{% endblock %}

{% block body %}

    <div class="fixed right-1 pt-6 pr-6">
        <a href="{{ path('displayOneAlbumAntiChrono', {idAlbum:albumIDofCurrentPhoto, titleAlbum:titleAlbum})  }}" title="fermer" class="modal-close px-2 py-2 text-xs rounded-lg text-gray-300 bg-red-700 hover:bg-red-500 hover:text-white transform transition duration-500">FERMER</a>
    </div>

    <section class="h-full lg:grid lg:grid-cols-12 -mt-12 flex-column">
        <div class="flex flex-col col-start-1 col-span-8 gap-4 justify-between p-4 m-4 bg-black border border-1 border-gray-600 shadow-lg rounded-lg">

            <h2 class="text-blue-400  italic">Album : <a href="{{ path('displayOneAlbumAntiChrono', {idAlbum:albumIDofCurrentPhoto, titleAlbum:titleAlbum})  }}" class="hover:text-gray-300 transform transition duration-500 underline">{{ titleAlbum | upper }}</a></h2>

            <div class="flex justify-between items-center">
                <a href= "{{ path('detailsPhoto', {titleAlbum:titleAlbum, idPhoto:idPhoto, status:'prev-photo' } ) }}" >
                    <div title="photo moins récente" class=" px-3 py-10 text-xl rounded-full text-gray-300 bg-blue-700 hover:bg-blue-500 shadow-md transform transition duration-500">
                    <i class="fas fa-chevron-left"></i>
                    </div>
                </a>

                <div class="px-36">
                    {% set equi = '' %}
                    {% set equi = selectedPhoto.file %}
                    {% if uploadImagesDestination is same as('local') %}
                        <img class="m-auto border border-1 border-blue-700 shadow-lg rounded-lg max-h-full" src='{{ asset('uploads/'~equi) }}' alt="photo gros plan">
                    {% else %}
                        <img class="m-auto border border-1 border-blue-700 shadow-lg rounded-lg max-h-full" src='{{ urlCloudinary~equi }}' alt="photo gros plan">
                    {% endif %}

                </div>
                <a href= "{{ path('detailsPhoto', {titleAlbum:titleAlbum, idPhoto:idPhoto, status:'next-photo' } ) }}" >
                    <div title="photo plus récente" class=" px-3 py-10 text-xl rounded-full text-gray-300 bg-blue-700 hover:bg-blue-500 shadow-md transform transition duration-500">
                        <i class="fas fa-chevron-right"></i>
                    </div>
                </a>
            </div>

            <div class="text-center text-base text-gray-600 font-normal pt-2 pb-6">
                <p class=" mb-1">
                    - Posté le {{ selectedPhoto.createAt | format_datetime('short', 'none', locale='en', pattern='dd/MM/yyyy')  }}, par : {{ selectedPhoto.auteur.username }} -
                </p>
                <p>
                    - Thématique : {{ selectedPhoto.album.theme.titre }} -
                </p>
            </div>
        </div>

        <div class="lg:text-base text-sm text-gray-600 col-span-3 gap-2 -mr-6 mt-4 h-screen grid grid-flow-col grid-rows-12">

{# carte loc #}
            <div class="bg-black border border-1 border-gray-600 shadow-lg rounded-lg p-4 row-start-1 row-span-1">
                <div class="flex justify-between">
                    <p>Localisation</p>
                    <a href="{{ path('add_place', {titleAlbum: titleAlbum, photoId:selectedPhoto.id,status:1 }) }}">
                        <i title="modifier ou ajouter le lieu" class="fas fa-plus-circle text-2xl text-blue-700 hover:text-blue-500 transform transition duration-500"></i>
                    </a>
                </div>
                {% if selectedPhoto.lieu %}
                    <div class="text-center text-lg text-gray-400">{{ selectedPhoto.lieu}}</div>
                {% else %}
                    <p class="italic text-center text-gray-400"> "Non renseigné ..."</p>
                {% endif %}
            </div>
{# carte loc #}

{# carte annee #}
            <div class="bg-black border border-1 border-gray-600 shadow-lg rounded-lg p-4 row-start-2 row-span-1">
                <div class="flex justify-between">
                    <p>Date</p>
                    <a href="{{ path('add_year', {titleAlbum: titleAlbum, photoId:selectedPhoto.id,status:1 }) }}">
                        <i title="modifier ou ajouter la date" class="fas fa-plus-circle text-2xl text-blue-700 hover:text-blue-500 transform transition duration-500"></i>
                    </a>
                </div>
                {% if selectedPhoto.annee %}
                    <div class="text-center text-lg text-gray-400">{{ selectedPhoto.annee}}</div>
                {% else %}
                    <p class="italic text-center text-gray-400"> "Non renseigné ..."</p>
                {% endif %}
            </div>
{# carte annee #}


{# carte tag #}
            <div class="bg-black border border-1 border-gray-600 shadow-lg rounded-lg p-4 overflow-auto row-start-3 row-span-1">
                <div>
                    <div class="flex justify-between">
                        <p>Sur la photo</p>
                        <a href="{{ path('add_new_tag', {titleAlbum: titleAlbum, photoId:selectedPhoto.id,status:1, }) }}">
                            <i title="ajouter une personne" class="fas fa-plus-circle text-2xl text-blue-700 hover:text-blue-500 transform transition duration-500"></i>
                        </a>
                    </div>
                    {% set showPersonne = true %}
                    {% if lienTagPhotoList %}
                        {% for lien in lienTagPhotoList %}
                            {% if lien.photo.id == selectedPhoto.id %}
                                {% for tag in tagList %}
                                    {% if  lien.tag.id == tag.id %}
                                        {% set showPersonne = false %}
                                        <div class="text-center text-gray-400">- {{ lien.tag.prenom }}  {{ lien.tag.nom }} -</div>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    {% if showPersonne is same as(true) %}
                        <p class="italic text-center text-gray-400">"Personne identifié ..."</p>
                    {% endif %}
                </div>
            </div>
{# carte tag #}

{# carte commentaire #}
            <div class="bg-black border border-1 border-gray-600 shadow-lg rounded-lg p-4 mb-4 overflow-auto row-start-4 row-span-3">
                <div>
                    <div class="flex justify-between">
                        <p>Commentaires</p>
                        <a href="{{ path('add_new_comment', {titleAlbum: titleAlbum, photoId:selectedPhoto.id,status:1 }) }}">
                            <i title="ajouter un commentaire" class="fas fa-plus-circle text-2xl text-blue-700 hover:text-blue-500 transform transition duration-500"></i>
                        </a>
                    </div>
                    {% set showComm = true %}
                    {% if commentaireList %}
                        {% for comm in commentaireList %}
                            {% set showComm = false %}
                            {%  if comm.id is even %}
                                <div class="flex justify-start">
                                {% else %}
                                    <div class="flex justify-end">
                                {% endif %}
                                    <div class="bg-gray-400 w-2/3 text-gray-800 rounded-xl my-2 p-2">
                                        <p class="font-bold">" {{ comm.texte }} "</p>
                                        <p class="text-xs text-right italic">Par {{ comm.auteurId.username }} - {{ comm.createdAt | format_datetime('short', 'none', locale='en', pattern='dd/MM/yyyy')  }} </p>
                                    </div>
                                </div>
                        {% endfor %}
                    {% endif %}
                        {% if showComm is same as(true) %}
                            <p class="italic text-center text-gray-400"> "Aucun commentaire ..."</p>
                        {% endif %}
                    </div>
                </div>
            </div>
{# carte commentaire #}

        </div>
    </section>

{% endblock %}

templates/display/displayComment.html.twig
<div class="px-28 py-10">
    <section class="bg-gray-700 rounded-lg">
        {% for comment in commentPhoto %}
                <p class="text-white text-center font-bold py-2 my-4">- {{ comment.texte }} - </p>
        {% endfor %}
    </section>
</div>

templates/display/displayPlace.html.twig
<div class="px-28 py-10">
    <section class="bg-gray-700 rounded-lg">
        <p class="text-white text-center font-bold py-2 my-4">- {{ currentPlace }} - </p>
    </section>
</div>

templates/display/displayTagg.html.twig
<div class="py-10">
    <section class="bg-gray-700 rounded-lg">
        {% for personn in taggedPersonns %}
            {% for item in personn %}
                <p class="text-white text-center lg:text-lg text-sm py-2 my-4">- {{ item.prenom}}  {{ item.nom }} - </p>
            {% endfor %}
        {% endfor %}
    </section>
</div>

templates/display/single-album.html.twig
{% extends 'base.html.twig' %}

{% block title %}Single Album{% endblock %}

{% block body %}

    {#  {%  include 'component/inputAddPhoto.html.twig' %} #}

    <section class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12">

        {% if listPhotoAlbum %}
            <p class="text-sm text-blue-400 italic mb-12"><a class="hover:text-gray-300 transform transition duration-500 underline" href="{{ path('home') }}">PAGE D'ACCUEIL_</a>
                <span>
                    <a class="hover:text-gray-300 transform transition duration-500 underline" href="{{ path('displayOneTheme', {idTheme:listPhotoAlbum[0].album.theme.id, titreTheme:listPhotoAlbum[0].album.theme.titre} )  }}" >/ Thème "{{ listPhotoAlbum[0].album.theme.titre }}"</a>
                </span>
                <span>/ Album "{{ titleAlbum }}" /</span>
                <span class="text-xs"> Toutes les photos</span>
            </p>
        {% else %}
            <p class="text-base text-2xl text-gray-400">Album Vide</p>
        {% endif %}

        <div class="flex justify-end mb-3 hover:text-red-400 text-gray-200 transform transition duration-500">
            {% if toggleBtn == true %}
                <a href="{{ path('displayOneAlbumChrono', {idAlbum:idAlbum, titleAlbum:titleAlbum} )  }}" >
                    <div><i class="fas fa-arrow-circle-up"></i> Plus ancien au plus recent <i class="fas fa-arrow-circle-up"></i></div>
                </a>
            {% else %}
                <a href="{{ path('displayOneAlbumAntiChrono', {idAlbum:idAlbum, titleAlbum:titleAlbum} )  }}" >
                    <div><i class="fas fa-arrow-circle-down"></i> Plus récent au plus ancien <i class="fas fa-arrow-circle-down"></i></div>
                </a>
            {% endif %}
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {% for photo in listPhotoAlbum %}
                {% set equi = '' %}
                {% set equi = photo.file %}
            <div class="h-80 w-full bg-gradient-to-b from-gray-600 to-gray-400 rounded-lg shadow-lg justify-center p-2 flex flex-col">
                <div class="h-4/6 mb-10">
                    <a href= "{{ path('detailsPhoto', {idPhoto:photo.id, titleAlbum:photo.album.titre, status:"view" } ) }}" >
                        {% if uploadImagesDestination is same as('local') %}
                            <img class="border border-1 border-blue-700 shadow-lg rounded-lg object-center object-cover h-full w-full" src='{{ asset('uploads/'~equi) }}' alt="Photo de couverture">
                        {% else %}
                            <img class="border border-1 border-blue-700 shadow-lg rounded-lg object-center object-cover h-full w-full" src='{{ urlCloudinary~equi }}' alt="Photo de couverture">
                        {% endif %}
                    </a>
                </div>
                <div class="text-center">
                    <p class="text-xs text-gray-800 font-normal">Posté le {{ photo.createAt | format_datetime('short', 'none', locale='en', pattern='dd/MM/yyyy')  }}</p>
                    <p class="text-xs text-gray-800 font-normal">Par : {{ photo.auteur.username }}</p>
                </div>
                    {% if is_granted('ROLE_ADMIN') %}
                        <div class="ml-auto">
                            <a href="{{ path('deletePhotoFromAlbum', {titleAlbum:titleAlbum, idAlbum:idAlbum, idPhoto:photo.id}) }}" title="supprimer la photo" onclick="return confirm('Confirmer la suppression de cette photo ?')" class="px-2 py-1 text-xs border border-solid border-blue-500 hover:border-red-700 rounded-full text-red-700 bg-transparent hover:bg-red-700 hover:scale-105 hover:text-white transform transition duration-500">
                                X
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </section>

{% endblock %}